## Tensor boolean masking

In [2]:
import numpy as np
import torch

In [3]:
vector  = torch.tensor([10, 20, 30, 40, 50])
vector

tensor([10, 20, 30, 40, 50])

## Boolean Indexing

In [4]:
vector[[True, False, True, True, False]]

tensor([10, 30, 40])

## Filtering the tensor

In [5]:
# broadcasting 
vector > 30

tensor([False, False, False,  True,  True])

In [10]:
vector[vector > 30]

tensor([40, 50])