## simple attention mechanism

In [2]:
import numpy as np
import torch
import math

### get the input

In [3]:
# input string
input_str = "Your journey starts with one step"

In [ ]:
# get the embeddings of all the tokens
inputs = torch.tensor([
   [0.43, 0.15, 0.89], # Your
   [0.55, 0.87, 0.66], # journey
   [0.57, 0.85, 0.64], # starts
   [0.22, 0.58, 0.33], # with
   [0.77, 0.25, 0.10], # one
   [0.05, 0.80, 0.55]  # step
])

In [5]:
# take journey as an example 
query = inputs[1]
query

tensor([0.5500, 0.8700, 0.6600])

### calculate attention scores

In [6]:
# attentions cores of journey wrt to all the embeddings
attention_scores_journey = torch.empty(inputs.shape[0])

# calculate the attention score with all embeddings
for index, embedding in enumerate(inputs):
    attention_scores_journey[index] = torch.dot(query, embedding)

attention_scores_journey    

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [7]:
attention_scores_journey.sum()

tensor(6.5617)

### calculate attention weights

In [8]:
# get the total attention scores
attention_scores_journey_sum = attention_scores_journey.sum()
attention_weights_journey = attention_scores_journey/attention_scores_journey_sum
attention_weights_journey

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])

In [9]:
attention_weights_journey.sum()

tensor(1.0000)

## apply softmax

In [11]:
weights = [0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656]

# calculate the e_total
e_total = 0
for value in weights:
    e_total += math.exp(value)

# divide every value in the weights by e_total
normalized_weights = [math.exp(value)/e_total for value in weights]    
normalized_weights

[0.163005260478708,
 0.17698809548436997,
 0.17647557352350096,
 0.16025759240191018,
 0.15695866228968697,
 0.16631481582182409]

In [12]:
def my_softmax(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

my_softmax(torch.tensor(weights))

tensor([0.1630, 0.1770, 0.1765, 0.1603, 0.1570, 0.1663])

In [13]:
normalized_weights = torch.softmax(torch.tensor(weights), dim=0)
normalized_weights

tensor([0.1630, 0.1770, 0.1765, 0.1603, 0.1570, 0.1663])

In [14]:
normalized_weights.sum()

tensor(1.)