### embedding logic using lookup table

In [1]:
import numpy as np
import torch

In [2]:
vocab_size = 10

dimensions = 5

In [3]:
lookup_table = torch.rand(vocab_size, dimensions, requires_grad=True)
lookup_table

tensor([[0.7636, 0.5259, 0.4834, 0.4182, 0.7869],
        [0.1616, 0.5462, 0.5604, 0.0624, 0.5584],
        [0.0054, 0.2487, 0.6415, 0.7104, 0.7602],
        [0.5853, 0.1434, 0.9947, 0.8732, 0.3498],
        [0.4065, 0.9427, 0.6522, 0.3346, 0.1604],
        [0.6791, 0.4509, 0.0936, 0.9027, 0.8518],
        [0.0334, 0.3723, 0.2200, 0.5746, 0.9147],
        [0.8262, 0.2401, 0.7808, 0.1711, 0.6117],
        [0.6223, 0.2587, 0.6338, 0.9158, 0.8372],
        [0.7399, 0.0373, 0.4041, 0.9182, 0.3356]], requires_grad=True)

In [4]:
lookup_table.shape

torch.Size([10, 5])

In [6]:
token_ids = torch.tensor([1, 6, 8, 9])

In [7]:
embeddings = lookup_table[token_ids]
embeddings

tensor([[0.1616, 0.5462, 0.5604, 0.0624, 0.5584],
        [0.0334, 0.3723, 0.2200, 0.5746, 0.9147],
        [0.6223, 0.2587, 0.6338, 0.9158, 0.8372],
        [0.7399, 0.0373, 0.4041, 0.9182, 0.3356]], grad_fn=<IndexBackward0>)

### Use tiktoken to generate embeddings

In [10]:
import tiktoken
tokenizer = tiktoken.get_encoding('gpt2')
tokenizer.n_vocab

50257

In [13]:
# create a lookup table
lookup_table = torch.randn(tokenizer.n_vocab, 5, requires_grad=True)
lookup_table

tensor([[ 7.6129e-01,  5.5725e-03,  1.1567e+00, -1.2345e-01, -1.2712e+00],
        [ 3.0040e-01, -1.4284e+00, -1.4346e-01, -3.0466e-01,  2.6656e-01],
        [-8.8768e-01, -1.4517e+00, -2.1636e-03,  2.9056e-01, -6.8680e-01],
        ...,
        [ 1.0259e+00,  5.0880e-01,  2.7824e+00,  1.2819e+00,  2.3305e-01],
        [ 1.5146e+00,  9.5352e-01, -8.3412e-01, -1.1323e-01,  6.8766e-01],
        [ 1.9646e+00, -8.3200e-02, -7.6602e-01, -1.0166e-01, -1.0269e+00]],
       requires_grad=True)

In [14]:
lookup_table.shape

torch.Size([50257, 5])

In [16]:
# input 
sentence = "I love machine learning"


# get the tokens for the sentence
token_ids = tokenizer.encode(sentence)
token_ids

[40, 1842, 4572, 4673]

In [17]:
# get the embeddings for token_ids
embeddings = lookup_table[token_ids]
embeddings

tensor([[-0.4341,  0.6292,  0.1053,  0.1505,  0.6571],
        [ 0.4179,  0.5637,  0.0720,  0.6190,  1.2069],
        [-1.3368,  0.7271,  0.3176,  0.2291, -1.1132],
        [-0.2606,  1.0183, -1.6306,  0.5652,  0.0052]],
       grad_fn=<IndexBackward0>)