## data sampling using sliding window with a dataset

In [1]:
import numpy as np
import torch
import tiktoken
from torch.utils.data import Dataset, DataLoader

In [2]:
with open(r"data.txt", "r") as file:
    raw_text = file.read()

### create a dataset with input and target tokens

In [5]:
class DreamLLMDataset(Dataset):
    def __init__(self, raw_text, context_length = 10, stride = 1):
        # craete the tokenizer
        tokenizer = tiktoken.get_encoding('gpt2')

        # create the tokens
        tokens = tokenizer.encode(raw_text)

        # store the input and target tensors
        self.input_ids = []
        self.target_ids = []

        # create the input and target tensors
        for i in range(1, len(tokens) - context_length, stride):
            input_chunk = tokens[i : i + context_length]
            target_chunk = tokens[i + 1 : i + context_length + 1]

            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)        
    
    def __getitem__(self, index):
        return self.input_ids[index], self.target_ids[index]

In [6]:
# create the dataset
dataset = DreamLLMDataset(raw_text=raw_text)

# craete a dataloader
data_loader = DataLoader(dataset=dataset, batch_size=5)

In [7]:
#  get the iterator
data_loader_iterator = iter(data_loader)

In [8]:
# load the first batch
next(data_loader_iterator)

[tensor([[  373,  3726,   284,   651,   845, 10032,   286,  5586,   416,   607],
         [ 3726,   284,   651,   845, 10032,   286,  5586,   416,   607,  6621],
         [  284,   651,   845, 10032,   286,  5586,   416,   607,  6621,   198],
         [  651,   845, 10032,   286,  5586,   416,   607,  6621,   198,   261],
         [  845, 10032,   286,  5586,   416,   607,  6621,   198,   261,   262]]),
 tensor([[ 3726,   284,   651,   845, 10032,   286,  5586,   416,   607,  6621],
         [  284,   651,   845, 10032,   286,  5586,   416,   607,  6621,   198],
         [  651,   845, 10032,   286,  5586,   416,   607,  6621,   198,   261],
         [  845, 10032,   286,  5586,   416,   607,  6621,   198,   261,   262],
         [10032,   286,  5586,   416,   607,  6621,   198,   261,   262,  3331]])]

In [9]:
next(data_loader_iterator)

[tensor([[10032,   286,  5586,   416,   607,  6621,   198,   261,   262,  3331],
         [  286,  5586,   416,   607,  6621,   198,   261,   262,  3331,    11],
         [ 5586,   416,   607,  6621,   198,   261,   262,  3331,    11,   290],
         [  416,   607,  6621,   198,   261,   262,  3331,    11,   290,   286],
         [  607,  6621,   198,   261,   262,  3331,    11,   290,   286,  1719]]),
 tensor([[ 286, 5586,  416,  607, 6621,  198,  261,  262, 3331,   11],
         [5586,  416,  607, 6621,  198,  261,  262, 3331,   11,  290],
         [ 416,  607, 6621,  198,  261,  262, 3331,   11,  290,  286],
         [ 607, 6621,  198,  261,  262, 3331,   11,  290,  286, 1719],
         [6621,  198,  261,  262, 3331,   11,  290,  286, 1719, 2147]])]

In [11]:
next(data_loader_iterator)

[tensor([[6621,  198,  261,  262, 3331,   11,  290,  286, 1719, 2147],
         [ 198,  261,  262, 3331,   11,  290,  286, 1719, 2147,  284],
         [ 261,  262, 3331,   11,  290,  286, 1719, 2147,  284,  466],
         [ 262, 3331,   11,  290,  286, 1719, 2147,  284,  466,   25],
         [3331,   11,  290,  286, 1719, 2147,  284,  466,   25,  220]]),
 tensor([[ 198,  261,  262, 3331,   11,  290,  286, 1719, 2147,  284],
         [ 261,  262, 3331,   11,  290,  286, 1719, 2147,  284,  466],
         [ 262, 3331,   11,  290,  286, 1719, 2147,  284,  466,   25],
         [3331,   11,  290,  286, 1719, 2147,  284,  466,   25,  220],
         [  11,  290,  286, 1719, 2147,  284,  466,   25,  220, 1752]])]